version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: waa-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: waa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-waa
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    depends_on:
      - postgres
    restart: always

  waa-app-be:
    build: .
    ports:
      - '3001:3001'
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: yarn start
    restart: always

volumes:
  postgres_data:
