export const UserPermission = Object.freeze({
  ACTIVATE_BY_EMAIL: 'ACTIVATE_BY_EMAIL',
  RESET_PASSWORD: 'RESET_PASSWORD',
  ACTIVATE_USER: 'ACTIVATE_USER',
  GET_PROFILE: 'GET_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  FORGOT_PASSWORD: 'FORGOT_PASSWORD'
})
